# Publish all joint states
# Creates the /joint_states topic necessary in ROS
hc10_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - joint_1_s
        - joint_2_l
        - joint_3_u
        - joint_4_r
        - joint_5_b
        - joint_6_t